# CHP 5 - Comparing multimodal total-, singly and unconstrained accessibility of Toronto's parklands [NOT DONE]

<!-- Required to number equations in HTML files -->
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

```{r include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  cache = FALSE,
  warning = FALSE,
  message = FALSE)
```


## Overview
This frames opportunities as hectares of parkland for one type, Large park, as all modes are present in the normative impedance. We will assume everyone walks, and hence the population of walkers is equal to the population at the origin. To keep it simple, just walking as a mode will be analysed, either 1 or 0 binary function at different thresholds. 

First, these assumptions will yield values of $V^0_i$, $V^T_i$ and $V^S_i$ as the accessible parkland along with per capita ratios in discussion with potential parkland service provision. 

Next, $M^0_j$, $M^T_j$ and $M^S_j$ as the accessible population along with per parkland ratios in discussion with potential population served. 


## Accessible parkland (for the population)

Focusing on the accessible number of parks: the following plot demonstrates a disaggregated version of figure above. Each plot demonstrates the number of parks that are accessible, by mode. Again, the embedded assumption is the number of parkland in the city is allocated to each DB based on the travel impedance of that mode's zone relative to all the travel impedance of all modes in the region.
[4 Toronto DB plots - featuring accessibility to all parks by mode]

[4 Toronto DB plots, summarised by neighbourhood - featuring accessibility to ONLY large parks by mode]

[4 Toronto DB plots, summarised by neighbourhood - featuring accessibility to ONLY small parks by mode]

[4 Toronto DB plots - featuring accessibility to all parks per capita by mode]

[summary table of top 5, middle 5, and bottom 5 neighbourhoods]


## Accessible population (to the parkland)

If interested in using totally-constrained accessibility as an indicator of service provision, conceptualing the 'market pontential' variant is useful to yield values of 'number of people that can access parks' for the zonal unit of question. 

The following is the access to people, by mode. Notably, it is not correlated with opportunities, as there is a mis-match in population and parkland in certain neighbourhood (see fig..X)
[4 Toronto DB plots - featuring accessibility to all people by mode]


The following is the access to people, by mode:
[4 Toronto DB plots, summarised by neighbourhood - featuring accessibility to people from ONLY large parks by mode]

[4 Toronto DB plots, summarised by neighbourhood - featuring accessibility to people from ONLY small parks by mode]

[4 Toronto DB plots - featuring accessibility to all people per parkland capita by mode]

[summary table of top 5, middle 5, and bottom 5 neighbourhoods]
